version: "3.9"

services:
  graphwar:
    build: .
    container_name: graphwar-server

    ports:
      - "20001:20001"
      - "20002:20002"
      - "20003:20003"
      - "20004:20004"
      - "20005:20005"
      - "20006:20006"

    volumes:
      - ./logs:/app/logs
      - ./:/app

    restart: unless-stopped