name: "Community roms"
ports:
  - 20001
  - 20002
  - 20003
  - 20004
  - 20005
  - 20006

eventLops:
  boos:
    threads: 4
    name_pattern: "BoosThread-${index}"
    daemon: true
  worker:
    threads: 12
    name_pattern: "WorkerThread-${index}"
    daemon: true

tracker:
  host: "www.graphwar.com"
  port: 23761
  auto_reconnect: true

servers:
  - name: "Community room: 1"
  - name: "Community room: 2"
  - name: "Community room: 3"
  - name: "Community room: 4"
  - name: "Community room: 5"
  - name: "Community room: 6"

#InfluxDB
metrics:
  enable: true
  host: "http://46.201.210.237:8086"
  token: "5R9t1_b1QsW4BT9Krz0Qu7N9mIEBsvb-lUeRtaPI1GN8tNPcQJ-QKxCfzCmEz_pDMwgJ623o99zn7hoLe_Hj2A=="
  bucket: "shared"
  org: "none"

welcome_messages:
  - ""


